### ISSUE TITLE
Enhancements available in win10 but not 11

### ISSUE THREAD

**Issue by ethano8225** [Falcosc/enable-loudness-equalisation#13]
Hello, previously I was able to use loudness EQ in the enhancements tab like normal (shown [here,](https://ibb.co/4f6jQK0) win 10). When using the headset on win11, seemingly using the same 'default drivers' (although they are updated, win10 shown above, vs win11 [here](https://ibb.co/GxBptDk)) it gives me no enhancements tab. I can manually add the registry strings (the main 3 and the hex/binary to enable loudness EQ) which shows the enhancements tab, just with no options underneath. 
i dont know why Gdrive detects reg folders as audio, but [here ](https://drive.google.com/file/d/1XeISZl3-wFrERKL8Nq_OnkIfIJ2El59N/view?usp=drive_link)is my Win10 Render folder, I went through and found both of the hyperX 'folders' [here](https://ibb.co/KFbR4tS)
[Here ](https://drive.google.com/file/d/12rFezstKQX_DnwQEoNHJP8h55WnxTnx5/view?usp=sharing) is my win11 Render folder, and you can find both the [hyperx folders AND 2 folders for airpod Pros](https://ibb.co/F7fh3bm) which HAD support for loudness EQ until a few days ago (it disappeared randomly, im not exactly sure what triggered it).
I might try to just import the old win10 hyperX 'folders' into both of the new HyperX 'folders', as even if it bricks my system, as frankly enough idc anymore (this system is a brick to me without Loudness EQ). If you reached this point, I want to thank you for taking the time reading this, as this has driven me crazy. Have a great rest of your day :)
ALSO - I know this isnt a specific problem with your software, but I figure you are by far the best person I could talk to, to get help on this issue.

**Comment by etan8225** [comment]
I would also like to say 2 more things- on windows10, the enhancements tab shows up [despite the fact that I have hyperX ngenuity installed](https://www.reddit.com/r/HyperX/comments/112utvl/comment/j90g80b/?utm_source=share&utm_medium=web2x&context=3), but on win11 whether I have ngenuity installed or not, it doesnt show up. If I install it, it actually shows completely different customization settings - on win10, it shows 7.1 surround sound, and on win11, it shows DTS X spacial bullsh*t (that I dont want) and an equalizer (like for individual frequencies). I can provide screenshots if wanted.

**Comment by Falcosc** [comment]
You can't find the reason for the behavior of the software/drivers because most of them are closed source or impossible to find the sources.

So it's all trial and error.
I lost my settings as well, for me, it was re-detection of my monitor and random Windows updates. That's why I scripted the whole thing. Now you just have to find out which settings are needed to get what you need.

Stuff like FORM_FACTOR and FULL_RANGE_SPEAKERS settings got only discovered while searching through the web. Some people told to set some unknown things to as fix and with some research I found the meaning and did prove it by setting values from known secondary audio devices.

So nothing new for you, just the information that there isn't any hidden thing where I can point your research. In this Repo you will just find stuff I stumbled over. A collection of 100s of contributions to get a nice automation for my issues :)

If you set stuff which your driver does disagree with, it could happen that your settings get purged on reboot. Take a look here: https://github.com/Falcosc/enable-bass-boost I found my cause and excluded them with my flag -noFakeProperties which makes it impossible to access the settings UI, but most features can be activated without UI access.

**Comment by etan8225** [comment]
Thank you for the quick response, and for sharing these solutions publicly! I've noticed a few similarities with drivers that support Loudness EQ across win10 and 11 (for ex. the "DeviceState" always being set to 0x00000004 with no other keys in that same spot), so in the next few days I'm going to be messing with practically all of the keys that I can to make this work. If I find a solution, I will add an update to this post saying what I did to make it work. 
Also, I have noticed that 2 of the main keys (for premix- and postmixeffectclsid) occasionally have different numbers added to them. So instead of {...},1 for premix and {...},2 for postmix, both of my computers had {...},5 {...},6 set as default. What does this mean/does it mean anything? I guess I'll figure it out lol
Anyways thanks again, me and many others appreciate the work you've done here!!

**Comment by Falcosc** [comment]
Keys are different across driver versions. So I already assumed that some of them will be incorrect across windows versions. In the worst case, you will even find differences across driver version.

**Comment by etan8225** [comment]
Alright so after relooking at everything again, I realized that during my transition of win10 to win11 I got a "replacement" for my headset (under warranty), received an ever so slightly different product, and I guess it has different drivers. The thing is, when I connect this "new" headset to my win10 pc, it detects the device as the OLD device with the old settings. Like it has the 7.1 surround sound with the loudness EQ enhancement available, instead of DTS:X which is what this new headset (supposedly) has... WTF is this HyperX. 

I think my next step will be try to install win10 on this laptop, and use the old headset's USB to add the drivers. That's the only hope I really have left, as when I tried to completely delete the "new headsets" drivers/dlls on win11, many of the drivers stayed in the system folders (despite me deleting them 'permanently')

**Comment by etan8225** [comment]
HALLELUJAH I GOT IT WORKING!! Thank you for your help my good sir! I created a [youtube video](https://youtu.be/mjiBkQOM6lc) that explained my process and also made a stupid [reddit post](https://www.reddit.com/r/HyperX/comments/15qhte9/force_loudness_equalizationbass_boost_on_hyperx/) in hopes this solution gets out to more people. I know you 'just did research' to find this solution, but without that, I would still be contemplating installing windows 10 on a windows 11-'only' laptop.
FYI - My keys were different, for ex {d04e05a6-...},1 was {d04e05a6-...},5 with a different corresponding value (look at the reddit post if you don't get what i mean 👍 )

**Comment by Falcosc** [comment]
You did add PKEY_FX_ModeEffectClsid and PKEY_FX_ModeEffectClsid these are pointing to the actual driver classes which will be more likely to be different.

What happens without overwriting PKEY_FX_ModeEffectClsid and what without overwriting PKEY_FX_ModeEffectClsid?

You can check the inf files if you are not sure which line you did actually overwrite and which where missing

That are your lines, PKEY_SYSFX_UiClsid is usually equal since this is used for the Windows UI
´´´
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},3 PKEY_SYSFX_UiClsid  {5860E1C5-F95C-4a7a-8EC8-8AEF24F379A1}
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},5 PKEY_FX_StreamEffectClsid {C9453E73-8C5C-4463-9984-AF8BAB2F5447}
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},6 PKEY_FX_ModeEffectClsid {13AB3EBD-137E-4903-9D89-60BE8277FD17}
´´´

And these are my drivers, and they didn't need these lines since they were already present in the inf
´´´
C:\Windows\INF\hdaudio.inf Microsoft 1.1 UAA Function Driver for High Definition Audio
FX_STREAM_CLSID  = "{62dc1a93-ae24-464c-a43e-452f824c4250}"  (PKEY_FX_StreamEffectClsid)
FX_MODE_CLSID    = "{637c490d-eee3-4c0a-973f-371958802da2}" (PKEY_FX_ModeEffectClsid)

C:\Windows\INF\oem60.inf Conexant High Definition SmartAudio (Notebook)
SRS3_SYSFX_SFX_CLSID  = "{1B917FE2-47D1-425D-A26E-AFCDBDA7A2E8}" (PKEY_FX_StreamEffectClsid)
SRS3_SYSFX_MFX_CLSID  = "{5B98E1AC-A670-4311-B4F8-DC25E30CFBFF}" (PKEY_FX_ModeEffectClsid)
´´´´

\Render\{DEVICE}\Properties\{a8b865dd-2e3d-4094-ad97-e593a70c75d6},5 does tell which inf is used

**Comment by Falcosc** [comment]
Since mircosoft driver uses the the classes like my intel driver, what happens if you use the microsoft ones in 5 and 6
FX_STREAM_CLSID  = "{62dc1a93-ae24-464c-a43e-452f824c4250}"  (PKEY_FX_StreamEffectClsid)
FX_MODE_CLSID    = "{637c490d-eee3-4c0a-973f-371958802da2}" (PKEY_FX_ModeEffectClsid)

Maybe it works, but only for loudness? Could be that your classes are just extensing the microsoft ones to get the microsoft features + your special features

If it would work, I would add 5 and 6 to the repo, but only overwrite if not existing. Then everybody could have at least Microsoft features.

**Comment by etan8225** [comment]
Well to start I will [happily upload the inf files, along with some other reg folders outlined below](https://drive.google.com/drive/folders/1Qwh4gL1SSyzbDIHQGvrTFLSs-79hLZfb?usp=sharing), I didn't add anything to the inf files / make any modifications myself. Matter of fact, when i try to find "sysfx", "fx",.. or anything like it, I can't seem to find anything of interest in oem286.inf (like the setting was never meant to be enable-able).

A couple of weird things I feel like I should mention:
I only realized my airpods had enhancements because they were glitching. Usually when they connect they don't have any enhancements, but OCCASIONALLY when disabling the "headset" feature (keeping "headphones" enabled), the enhancements tab would pop up while showing "2 - (name)'s Airpods Pro" instead of just "(name)'s Airpods Pro" in the control panel. Because of that, I searched through the Render folder, and found like 8 different folders for the Airpods. I decided to steal from the one that had the most-similar looking FxProperties folder when comparing it to my Win10 HyperX FxProperties folder (that still works with loudness EQ). I then just singled out the 3 lonely {d04e05...} keys(strings?) in that folder, and essentially copy and pasted those, and it worked. I can only assume it worked because both use Intel's driver, even though one is a bluetooth and the other is a USB driver.

Also, I notice there are 2 entirely different installations of HyperX in my Render folder. One shows "DTS audio effects on hyperx relay headset" and the other doesnt have that entry AT ALL, like in the spot where "Microsoft Home Theater Audio Effects" would be. The non-working one uses the WDMA setup for usb's (wdma_usb.inf), and the one that works uses Intel's smart sound tech for usbs (oem286.inf). I also included the 'working' and 'non-working' reg file for those specific folders (and hdaudio.inf, since you asked). I would link you my HyperX ini file as well, but I'm still learning a lot about computers so I'm not so sure where that is stored. If you point it out to me, I'll happily add it to the drive folder so you can take a look.

I'll test the alternate strings very soon and provide an update. BUT "if it aint broke, dont fix it", so I'll be handling this part with much more care than I was before.

final comment: the broken hyperX folder also has multiple entries in a {d3993a3f-...},5 string that the working one does not. You can see that for yourself in the reg files I sent, its almost like that could offload where those effects are handled (or something?)

**Comment by Falcosc** [comment]
It's just about finding out if the well known class IDs work for all drivers and it was just an issue about pre-fx/post-fx VS fx-stream/fx-mode 
Or if some drivers don't work with the known class Ids.

Is your hyperX the oem286? It is a Intel® Smart Sound Technology for USB Audio
You will find the hyperX inf if you check which inf is configured in \Render\{DEVICE}\Properties\{a8b865dd-2e3d-4094-ad97-e593a70c75d6},5 of your hyperX audio device

**Comment by etan8225** [comment]
Ok so, clearly you have much more understanding in this topic than I do, but I understand the 'test' you are talking about. When I changed `{d04e05a6-...},5` to `{d04e05a6-...},1` and `{d04e05a6-},6` to `{d04e05a6-...},2` , keeping the same "bluetooth classes", it still worked (shown [here](https://ibb.co/By5tKwC)). 
and the only reason i said 'i dont want to fix it if it aint broken' is because i have no idea how these audio drivers were installed. For some reason when the last audio drivers were installed, intel audio was not available when "compatibility check" was enabled. Same thing currently when I try to change the intel drivers, the generic usb audio supposedly "isnt compatible". i have no idea what that actually means, but im happy that i got here lol

**Comment by Falcosc** [comment]
What about

```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},5 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},6 = "{637c490d-eee3-4c0a-973f-371958802da2}"
remove 1
remove 2
```

and final one, the version from the script:

```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},1 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},2 = "{637c490d-eee3-4c0a-973f-371958802da2}"
remove 5
remove 6
```

**Comment by etan8225** [comment]
Ooh. That last comment actually made me re-test everything, and it made me realize I hadn't properly tested the Loudness EQ in the first place. I think simply seeing the option actually appear for once made me too giddy and I jumped to a conclusion, my apologies.

BUT, I think I have found the real culprit. When I reinstalled the Intel Smart Sound BUS drivers as a "high definition audio device", as was recommended [here](https://www.intel.com/content/www/us/en/support/articles/000058422/intel-nuc.html), a different INF file appeared. [oem61.inf](https://pastebin.com/AyUHRmLA), and if you look at that shortened version (modified carefully to remove unnecessary files/lines obviously used by other headsets, 200 lines total), you'll see what I mean. Some examples:

`DTS_SFX_CLSID       = "{8B778F49-83A0-4EE9-896A-ED52903EDF1F}"`
`DTS_MFX_CLSID       = "{AD1F2B64-646D-43DB-9F29-08324E9A94E8}"`
`PKEY_DTS_APO4X_KEY              = "{7A8B74C8-FA66-4460-8542-D6119C59E9D4}"`
`PKEY_DTS_CONFIG_FILE            = "{7A8B74C8-FA66-4460-8542-D6119C59E9D4},2"`
`PKEY_FX_Association	            = "{D04E05A6-594B-4FB6-A80D-01AF5EED7D1D},0"`
`PKEY_CompositeFX_StreamEffectClsid   = "{D04E05A6-594B-4fb6-A80D-01AF5EED7D1D},13"`
`PKEY_CompositeFX_ModeEffectClsid     = "{D04E05A6-594B-4fb6-A80D-01AF5EED7D1D},14"`
`PKEY_SFX_ProcessingModes_Supported_For_Streaming = "{D3993A3F-99C2-4402-B5EC-A92A0367664B},5"`
`PKEY_MFX_ProcessingModes_Supported_For_Streaming = "{D3993A3F-99C2-4402-B5EC-A92A0367664B},6"`
Does any of this look promising? Would it be (even theoretically) possible to edit this inf file to support effects? Again, I appreciate your help!

**Comment by Falcosc** [comment]
It is just a config file, removing things there will not help much.

It just defines how the registry will be written based on the logic in the drivers. So I only use the inf file to check which class Ids where known during the driver development.

Did any of the pre-fx/post-fx VS fx-stream/fx-mode settings work? Either with windows class Ids or with bluetooth class ids?

```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},5 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},6 = "{637c490d-eee3-4c0a-973f-371958802da2}"
remove 1
remove 2
```
```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},1 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},2 = "{637c490d-eee3-4c0a-973f-371958802da2}"
remove 5
remove 6
```
```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},5 = "{C9453E73-8C5C-4463-9984-AF8BAB2F5447}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},6 = "{13AB3EBD-137E-4903-9D89-60BE8277FD17}"
remove 1
remove 2
```
```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},1 = "{C9453E73-8C5C-4463-9984-AF8BAB2F5447}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},2 = "{13AB3EBD-137E-4903-9D89-60BE8277FD17}"
remove 5
remove 6
```

If none of them work, you would need to switch the driver until you find one which works with the known good combination:
```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},1 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},2 = "{637c490d-eee3-4c0a-973f-371958802da2}"
remove 5
remove 6
```

To test you only need to restart audio service, like you see in the powershell script.

**Comment by etan8225** [comment]
OMFG what a joke of an OS. I figured win11 was the issue at heart, so I installed win10, and would you look at that! The "known strings" work as long as the first two are set to ,5 and ,6 instead of ,1 and ,2 (exactly how my headphones were set up on my old device). I also had to delete 2 extra strings from
`{d3993a3f-99c2-4402-b5ec-a92a0367664b},6`
leaving the value 
`{C18E2F7E-933D-4965-B7D1-1EEF228D2AF3}`
as that is how it was on my old device. I will leave this open for tonight just in case the problem comes back, but since my headphones aren't being setup by an "oemNN.inf" anymore, im suspecting all is well!
And yes, I have actually tested this time. I can tell the gain is actually being increased, gunshots are greatly reduced, and I can hear footsteps like normal. Again, thank you for all the help. I will check if those other bluetooth strings are still on this device, and if they are, I will test them tomorrow.  : )

**Comment by etan8225** [comment]
None of the combinations _actually_ worked in win11 AFAIK. The first time I added the strings 
```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},1 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},2 = "{637c490d-eee3-4c0a-973f-371958802da2}"
```
with the universal {d04},3 value {586..} as well, the setting showed up. Since the setting "just worked" in win10, I assumed that it would also "just work" on win11. ALSO, the enhancements tab had showed up before but without the Loudness EQ options, so when I finally saw them for the first time I assumed it was going to work. When you made the comment about "the setting never disappearing", I realized my major mistake and tested if the setting actually applied, and it did NOT. I then tried all of the other values in "Test A, C and D". Even though the loudness eq option was there for EVERY iteration, none of the values actually work in practice. 

When I switched over to win10, I set 
```
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},5 = "{62dc1a93-ae24-464c-a43e-452f824c4250}"
{d04e05a6-594b-4fb6-a80d-01af5eed7d1d},6 = "{637c490d-eee3-4c0a-973f-371958802da2}"
```
As that is how my headphones are set up on my old win 10 machine, I also deleted 2 extra values from that {d339..},6 as stated before. Even though that is just a setting for "PKEY_MFX_ProcessingModes_Supported_For_Streaming", it seemed like there was some type of "movie mode" and "communication mode" set up, but I didn't need 'em and I wasn't sure if it was effecting the enhancements so I deleted the extra strings. Also, these extra strings were not present in any other sound device on my system, all the other ones just had a single {C18..} value associated with it, so I figured goodbye & good riddance.
After many restarts, installing updated software, even downloading the new realtek audio drivers, the setting is still there and it actually works. I figure I'll upload my current working win10 reg, [here](https://drive.google.com/file/d/1YJcVrjTOoCkFyWbPjLNgrgdIr9KbcEQI/view?usp=sharing).

If I can find those other "bluetooth" strings on this system, I will try them out, but I'm not entirely sure they are still here after reinstalling everything.

**Comment by Falcosc** [comment]
Like this? 

| Win10 | Win11
-- | -- | --
TestA | yes | no
TestB | ? | no
TestC | ? | no
TestD | ? | no

**Comment by etan8225** [comment]
Yes, currently that is how the "working chart" would look like, at least for my machine. I think there is a couple of major takeaways from this though, as during this I have done quite a bit of research in how audio drivers are set up (although, this may not be applicable to every scenario as there are clearly many ways a device could be set up)

From [this github](https://github.com/dechamps/APO): (i realized i messed this part up. but this github has a LOT of good, condensed info. In particular, use Find to search for "The most important properties are those that control which sAPOs are used". it also says "If any SFX, MFX or EFX are present, then LFX and GFX are ignored". AKA, If `{d04..},5 ,6 OR ,7` is present, `,1 and ,2` are completely ignored.

From what I can tell, there is also a large amount of ways that a device could be set up to essentially prevent MS sysfx from working. specifically in the INF files by checking for a couple of things- a lack of `mssysfx.CopyandRegister` in the "Needs" section (typically where `KS.Registration` and/or `WDMAUDIO.Registration` is), if the audio device is specifically using kernel streaming mode (like mine was, i believe) you can look for [`KSPROPERTY_AUDIO_LOUDNESS`](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/ksproperty-audio-loudness) (or really any "KS" string that isn't `KSCATAGORY_AUDIO, KSCATAGORY_RENDER, KSCATAGORY_CAPTURE, or KS_NODETYPE_xxxxx`). If you can find the `(PKEY_)FX_UIClsid` in the inf, and it is not set typically (for example my headphones having no GFX and LFX, instead having SFX and MFX) you can try to throw in the "known good" clsid's into there, but there is no guarantee it will actually work, as shown on my win11 pc. I think a major, major part of this was the inclusion of that "oem61.inf" which did not include `mssysfx`, and had a "[`KS_TOPOLOGY`](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/audio-topology-nodes)" (which is essentially short for "this uses kernel streaming mode(?i think), and also separate drivers for audio processing/enhancement"). 

Now, the real question is, WHY DO MY HEADPHONES FORCE ME TO USE A DIFF DRIVER ON WIN11? And yes, I tried to use microsoft's updated "high definition audio driver" from win11, updated on the SAME day as windows 10's (the win10 ones work for these headphones), and yet when they try to install they fail. The only difference is the build version. Just like the OS (win11), a complete fail. Lol. 

Last note, I checked for the other CLSId's {C9453E73..} and {13AB3EBD...} and yet they are not on my system anymore. Just the normal ones from microsoft. 
Regardless, I'm somewhat curious if I can "change" the FX mode from S/M-FX to L/G-FX, AKA, if i can change ,5 and ,6 to ,1 and ,2 with no problems..? If so, can your script assume the user has ,5 and ,6 (and ,7?), delete those, and replace them with ,1 and ,2? I'll happily test that soon.

**Comment by Falcosc** [comment]
My Notebook audio jack also uses StreamEffectClsid and ModeEffectClsid. So it wasn't a one time thing. It's pretty common that intel drivers use Pre and PostMixEffect class ids while other drivers often use StreamEffectClsid and ModeEffectClsid
