### ISSUE TITLE
FxProperties is missing error

### ISSUE THREAD

**Issue by mrxt0098** [Falcosc/enable-loudness-equalisation#18]
hello when im type name of my device i get this error:

FxProperties is missing, it is very likely that import of C:\Users\POUYAF~1\AppData\Local\Temp\SoundEnhancementsTMP.reg does not work.
Please check if following path got created or create it manually: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render\{fb78e069-d181-4b48-8c77-1faa28e6e963}\FxProperties
import loudness activation into registry
Restart Audio to apply registry settings

![Screenshot (326)](https://github.com/Falcosc/enable-loudness-equalisation/assets/135238006/670d2abf-8602-492a-9901-b5c52a24f788)

**Comment by Falcosc** [comment]
I can't tell you anything else then the message already tells you to do.

If you don't understand what it is saying, I recommend stop there and call for tech support. Otherwise, just follow what the message suggests. :)

**Comment by zereshk3** [comment]
> I can't tell you anything else then the message already tells you to do.
> 
> If you don't understand what it is saying, I recommend stop there and call for tech support. Otherwise, just follow what the message suggests. :)

don't want to be a bother, but i was having the same problem. don't have enough knowledge in registry editing, i don't actually know there should be a key with FxProperties name or a folder.

**Comment by Falcosc** [comment]
Then you can't figure out if the problem is that your FxProperties key is missing because of an incompatible driver, or if you have Problems applying the registry changes.

The folder needs to be there since only system can create it, an Admin user can not create the folder. Usually driver installations create this folder, since they use System instead of Admin.

Please don't proceed without having somebody on hand which is familiar with registry adjustments. Don't play around with manual fixes of it if you don't understand it. But since the folder is missing, it is unlikely to work with this driver anyway.

**Comment by zereshk3** [comment]
> Then you can't figure out if the problem is that your FxProperties key is missing because of an incompatible driver, or if you have Problems applying the registry changes.
> 
> The folder needs to be there since only system can create it, an Admin user can not create the folder. Usually driver installations create this folder, since they use System instead of Admin.
> 
> Please don't proceed without having somebody on hand which is familiar with registry adjustments. Don't play around with manual fixes of it if you don't understand it. But since the folder is missing, it is unlikely to work with this driver anyway.

ok, thx anyway for clarifying... 
funny thing is, i didn't have any problems with my last windows, and the loudness applied without any problem but today i decided to reinstall the windows and this happened!! i was using the same driver in both installation. so? it might be some other software that i used. thx anyway.

**Comment by Falcosc** [comment]
Maybe the fx things got created with an older version of your drivers, possible even got installed automatically long time.
It is possible to create the fx folder by hand by changing the permissions from system to admin, but if the folder is missing you are likely to miss the needed binaries to actually hear a difference between on and off. 
So I would not recommend forced folder creation because it is unlikely to help.

**Comment by zereshk3** [comment]
not likely. been using this driver for a long time. it's an old driver for Realtek ALC892. 

been using equalizer apo to get surround sound. the loudness option were there before installing the APO, but it was gone after installing the APO(i could keep it by enabling it before installing the APO), till i found your work and it worked on my last windows, don't know why it doesn't work now...
the problem started when i tried to use the ART guide for warzone. it was working till the windows reinstallation. :(

haven't tried a nahimic driver for long time so i don't think it could've been a driver's doing.

**Comment by Falcosc** [comment]
The main problem with this is how every driver package does install stuff without documentation. And if you combine this with automatic driver updates like windows does it, you end up in a state where it is impossible to find out which driver or which software did install and register the fx features like the software which is used to post-process the audio for loudness equalization.

**Comment by zereshk3** [comment]
True, been going at it for half a day now, couldn't figure it out yet. but i guess it has something to do with me installing atmos at some time(maybe).
funny thing, i just saw something about fx sound and encoder in the ghost windows(it's a light version) it says exactly what i need!! fx sound installation!!! should i be worried?
