### ISSUE TITLE
Main Branch .PS1 issue

### ISSUE THREAD

**Issue by ArtIsWar** [Falcosc/enable-loudness-equalisation#23]
Rewording to clarify:

The current script in the main branch does not work - whenever I run the script on an audio device, Powershell shows "importing..." etc but the enhancements tab is not actually added. When I run the script from [here](https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/166d8c17b1d68b52d33ea241748dc4b3bc09e9ba/EnableLoudness.ps1), it works properly.

**Comment by Falcosc** [comment]
Have you tried my fix from 8 hours ago?
If yes, please share %TMP%/SoundEnhancementsTMP.reg result from the old and the new version. After the fix, they are equal on my system.

**Comment by ArtIsWar** [comment]
Reposted for clarification before retesting the main or checking update. Apologies. Main branch .ps1 functions now. Thank you!

**Comment by Falcosc** [comment]
There was a strange bug with "reg query", it took forever to return the result despite only searching a pretty narrow segment of the registry. I don't know what was happening on other people's computers, but the powershell cmdlet solution of the same search expression did work around this issue. Since the response is a bit differently, it did break the registry import.

How did you know that something was wrong? Do you download it regularly to check for new stuff?

**Comment by ArtIsWar** [comment]
I keep the invoke command handy to enable on systems that don't have LEQ available for gaming. Tried it and it didn't function, tried troubleshooting, found the other branch and it worked. This is wonderfully helpful work, so I figured I'd contribute any issues I found.

Cheers!

**Comment by Falcosc** [comment]
Wasn't aware that this option is missing on gaming systems. I usually see it missing on HDMI of Intel Graphics. And since you can't amplify monitor speakers a lot, it is impossible to hear audio streams with not enough gain.
And since HDMI audio devices sometimes get reinstalled, it was a pain to always put these entries in the random audio device id folder. But nobody is using monitor speakers for gaming.

**Comment by ArtIsWar** [comment]
Most Realtek USB 2.0 labeled drivers can't be rolled back to a generic driver with the enhancements tab, where your script fixes entirely!

**Comment by ArtIsWar** [comment]
Fun fact, with Equalizer APO installed FIRST as LFX/GFX, you can enable loudness EQ on a virtual cable, effectively adding LEQ to any system. Thank you again for all your work!
